# Generated by Django 6.0.7 on 2026-08-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
