# Generated by Django 6.0.7 on 2026-08-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_college_user_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='university',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year_of_study',
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
